### ISSUE TITLE
allow more barcode formats

### ISSUE THREAD

**Issue by pajowu** [zerforschung/schnelltesttest.de#11]
right now we only support ean. some quicktests don't have those, but a PZN or some other barcodes instead. we should check which of those are actually used and enable them in quaggajs

**Comment by maxoe** [comment]
ITF-14/SCC-14 

Apparently, the very common "Beijing Hotgen Biotech Co., Ltd. Novel Coronavirus 2019-nCoV Antigen Test (Colloidal gold)" uses this type for their cardboard packaging version of the test kit

**Comment by pajowu** [comment]
We also need PZN, as some tests sold by pharmacies only have those

**Comment by Wikinaut** [comment]
This one does not work:
![grafik](https://user-images.githubusercontent.com/1151915/150390703-a1bfd30c-705f-4ff9-9dd4-fddd8894d3b3.png)

**Comment by Wikinaut** [comment]
This one works when positioned "below" the screen barcode pattern:
![IMG_20220120_181716](https://user-images.githubusercontent.com/1151915/150391180-9bf5d8bb-bd6a-4484-8940-b6b676abc313.jpg)
![IMG_20220120_181744](https://user-images.githubusercontent.com/1151915/150391243-84bbf310-158e-4dc5-b3ac-eb9fd5435ad3.jpg)

**Comment by Jumper78** [comment]
Code128 works now! Thank you @ubahnverleih !
