### ISSUE TITLE
Explicit Button to allow camera access

### ISSUE THREAD

**Issue by LilithWittmann** [zerforschung/schnelltesttest.de#45]
We are getting more and more support requests for camera access because people rejected it once. An explicit button to grant it might help some people.

**Comment by BengtHagemeister** [comment]
Unfortunately programatically asking for camera access **again** is not really possible. All browsers handle this a bit differently but with the effect that the user itself needs todo some non-website specific action to fix this.

- Chrome (Chromium): Hitting deny will add the webpage to a permanent blocklist (chrome://settings/content/camera). The user needs to remove the page before requesting is allowed again.
- Firefox & Safari: Hitting deny (without checking "remember this" in firefox) will add the webpage to a temporary blocklist - which is emptied after the user refreshed the page.

A possible solution would be to add a description (maybe even personalized to the users browser) to the `NoPermissionsModal` on how to ask for permission manually again.

Some more information on this topic: https://stackoverflow.com/questions/15993581/reprompt-for-permissions-with-getusermedia-after-initial-denial
