### ISSUE TITLE
Search only works for first word in name

### ISSUE THREAD

**Issue by LilithWittmann** [zerforschung/schnelltesttest.de#50]
https://twitter.com/SuperbassWP/status/1484911479031844871?s=20

**Comment by pajowu** [comment]
it's not only the first word in the name, but the location seems to play some rule. #51 should fix this

**Comment by emtiu** [comment]
Can confirm for some specific search terms: https://twitter.com/emtiu/status/1485195868466827265

**Comment by tmechen** [comment]
typo (for json file) with #53

**Comment by StefanLobbenmeier** [comment]
Not sure if that’s a separate issue, but today I struggled to find „LUNGENE“ on the site. Only with the PDF of the RKI I was able to determine that it’s actually called „CLUNGENE“ but the cover of the product makes this hard to see:

![30E007B2-66BB-4B38-B256-721885830CA5](https://user-images.githubusercontent.com/36509607/150814723-cfd7e4ed-c740-415d-9b83-e99a12dc8e10.jpeg)

**Comment by pajowu** [comment]
Fixed by #63
