### ISSUE TITLE
Link to PEI dossier page broken

### ISSUE THREAD

**Issue by j3po** [zerforschung/schnelltesttest.de#78]
PEI Website changed... So the [current link to the PEI page](https://www.pei.de/SharedDocs/Downloads/DE/newsroom/dossiers/evaluierung-sensitivitaet-sars-cov-2-antigentests-excel.xlsx?__blob=publicationFile) on the result page is broken.

Link to PEI infopage regarding the tests is now [https://www.pei.de/DE/newsroom/dossier/coronavirus/coronavirus-inhalt.html?cms_pos=8](https://www.pei.de/DE/newsroom/dossier/coronavirus/coronavirus-inhalt.html?cms_pos=8)

Checked on 2022-07-14

**Comment by basisbit** [comment]
From the above mentioned "new" link:
> Die Marktübersicht in der BfArM-Liste nach § 1 Absatz 1 Satz 6 TestV (alt) sowie die Liste mit der Vergleichenden Evaluierung der Sensitivität von SARS-CoV-2-Antigenschnelltests werden damit eingestellt.

So, that link is not really helpful any more either.
The closest thing to a new usable link would probably be this:
> https://health.ec.europa.eu/health-security-and-infectious-diseases/crisis-management/covid-19-diagnostic-tests_de#gemeinsame-liste-der-corona-antigen-schnelltests

Unfortunately, that list doesn't seem to be published in a usable and easily sortable format any more.

**Comment by snorreflorre** [comment]
An archived version of the spreadsheet can be downloaded at [web.archive.org](https://web.archive.org/web/20220630104638/https://www.pei.de/SharedDocs/Downloads/DE/newsroom/dossiers/evaluierung-sensitivitaet-sars-cov-2-antigentests-excel.xlsx?__blob=publicationFile&v=17).

**Comment by ikarisan** [comment]
What a crap. A good example for "how to make a bad thing even worst". :( 

@basisbit Yes, you have to parse the "Clinical performance of the devic" column and search for strings like "Sensitivity of xxx% at Ct < 25" if it comes from the PEI. Or maybe "Relative specificity overall xx.x%; relative sensitivity (n=zzz) overall xx.x% (Ct < xx)." or... :( :( 

Maybe this list is more helpful: https://covid-19-diagnostics.jrc.ec.europa.eu/devices 

CSV: https://covid-19-diagnostics.jrc.ec.europa.eu/devices/export/csv
JSON: https://covid-19-diagnostics.jrc.ec.europa.eu/devices/export

**Comment by yuki-93** [comment]
I created PR https://github.com/zerforschung/schnelltesttest.de/pull/81 but didn't looked into the issues before. So this PR has the archived version served from PEI itself. 

But I'm not sure, if the mentioned sources here are a better ressource for the future 🤔

**Comment by pajowu** [comment]
Closed in #81
